add the task to open the documentation specific of the template and python3Console documentation
toradex/vscode-torizon-templates pull request #34
Opened 2023-01-13 19:04 UTC by andreriesco

Signed-off-by: Andre Riesco <andre.riesco@toradex.com>
Related-to: TIE-730

2023-01-14 00:20 UTC, microhobby commented on scripts/createFromTemplate.ps1
> +                    $_ -replace "__templateFolder__",$(Split-Path -Path $templateFolder -Leaf)
We have the `$template` variable that is the "name" of the template that can be used here

2023-01-14 00:21 UTC, microhobby requested changes

2023-01-14 00:21 UTC, microhobby commented on scripts/createFromTemplate.ps1
>                  } | Set-Content $a
Please add a break line here

2023-01-14 00:24 UTC, microhobby requested changes

2023-01-14 00:24 UTC, microhobby commented on scripts/createFromTemplate.ps1
> +                    # Get just the last string of the path, which is the name of the folder of the template
Let's keep the code and comments where possible with 80 columns. The code style is not specified, I know, but I'll open an issue for that.

2023-01-16 16:46 UTC, microhobby requested changes

2023-01-16 16:46 UTC, microhobby commented on assets/tasks/common.json
> +            "icon": {
add here:

```json
"presentation": {
                "echo": false,
                "reveal": "never",
                "focus": false,
                "panel": "shared",
                "showReuseMessage": false,
                "clear": true
            },
```

so the output panel is not presented and focused, catching the attention ...

2023-01-16 16:47 UTC, microhobby requested changes

2023-01-16 16:47 UTC, microhobby commented on assets/templatesDocumentation/python3Console/README.md
> +  <source src="../common/python3/createEnvPython3.mp4" type="video/mp4">
This is returning `Error 401`, to solve this we will host the files on https://github.com/toradex/torizon-experimental-torizon-ide-v2-docs to not leave the repo here overloaded.

2023-01-16 16:51 UTC, microhobby requested changes

2023-01-16 16:51 UTC, microhobby commented on assets/tasks/common.json
> +            "problemMatcher": "$msCompile",
Also here, add the `presentation` definitions

2023-01-16 17:17 UTC, microhobby commented
The video:

https://user-images.githubusercontent.com/2633321/212734759-54852563-cc33-4f63-90ad-2509907b647f.mp4

2023-01-17 19:38 UTC, andreriesco commented
@microhobby I updated this MR with what we discussed, getting the README.md and all the rest of the media documentation (images, videos, etc) from the newly created [vscode-torizon-templates-documentation](https://github.com/toradex/vscode-torizon-templates-documentation) repo. Please review

2023-01-18 05:25 UTC, microhobby commented
LGTM

2023-01-18 05:25 UTC, microhobby approved these changes

2023-01-18 05:27 UTC, merged